---
title: "Exploratory Plots"
author: "Hailey Quintavalle"
date: "2023-09-04"
output: html_document
---


```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(stringr)
```


```{r message=FALSE, warning=FALSE}
# read in the data manually
raw_bechdel <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
movies <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')
```


```{r}
hist(raw_bechdel$year)
hist(movies$year)
hist(as.numeric(movies2$domgross))
hist(as.numeric(movies2$intgross))
```


```{r}
movies <- movies %>% mutate(binary_test = if_else(binary == "PASS", 1, 0))
table(movies$binary_test)
```

```{r}
hist(movies$imdb_votes)
hist(movies$imdb_rating)
plot(movies$imdb_votes~movies$imdb_rating)
```

```{r}
movies %>% ggplot(mapping = aes(x =  imdb_rating)) +
  geom_histogram()
```



-------------------------------------------------------------------------------------------------------

```{r}
summary(lm(binary_test~ + budget + year, data = movies2))
```

# Look at plot descriptions
# make everything lowercase
# filter into stringr
# seach for "women" ?

```{r}
movies$plot <- str_to_lower(movies$plot)
# movies %>% filter(str_detect(plot, " woman | women | she | her | girl "))

movies <- movies %>% mutate(women = str_detect(plot, " woman | women | she | her | girl "))

movies %>%
  ggplot(. , mapping = aes(x = factor(women), y = imdb_rating)) +
  geom_boxplot()

```

```{r}
movies %>%
  ggplot(. , mapping = aes(x = factor(women), y = year)) +
  geom_boxplot()
```



```{r}
movies %>% 
  ggplot(. , mapping = aes(x = factor(women), y = binary_test, color = clean_test)) +
  geom_jitter()
```

ok = passes test
dubious = passes test, but still biased
men = women only talk about men
notalk = women don't talk to each other
nowomen = fewer than two women

```{r}
movies %>%
  ggplot(. , mapping = aes(x = factor(binary), y = imdb_votes)) +
  geom_boxplot()
```


```{r}
movies %>%
  ggplot(. , mapping = aes(x = factor(binary), y = year)) +
  geom_boxplot()
```

```{r}
movies %>%
  ggplot(. , mapping = aes( y = imdb_rating, color = clean_test)) +
  geom_boxplot()
```


```{r}
movies %>%
  ggplot(. , mapping = aes( y = budget, x = factor(women), color = women)) +
  geom_boxplot()
```

```{r}
movies %>%
  ggplot(. , mapping = aes( y = budget, x = factor(binary_test), color = women)) +
  geom_boxplot()
```


```{r}
movies %>%
  ggplot(. , mapping = aes(x = factor(binary), y = women, color = clean_test)) +
  geom_jitter()
```

```{r}
movies %>% filter(binary_test == 0, women == "TRUE") %>% select(title, plot) # is binary variable really accurate?
```

# why certain movies called dubious?
# tidytext library




