---
title: "Regression Analysis"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(broom)
movies2 <- read.csv("movies2.csv")
movies2 |> as_tibble() 
```

```{r}
movies2 <- movies2 %>% mutate(binary_0 = ifelse(binary == "PASS", 1, 0))

mod_year <- glm(binary_0 ~ budget_2013 +
                  year + 
                  imdb_rating,
                data = movies2, family = "binomial") 
summary(mod_year) 
```

```{r}
library(modelr)
grid <- movies2 |>
  data_grid(
    year = seq_range(year, n = 4),
    binary_0 = c(0, 1),
    imdb_rating = seq_range(imdb_rating, n = 6),
    budget_2013 = seq_range(budget_2013, n = 8)
    )


aug_year <- augment(mod_year, newdata = grid, se_fit = TRUE)
aug_year <- aug_year |> mutate(.pi = exp(.fitted) / (1 + exp(.fitted)))


ggplot(data = aug_year, aes(x = budget_2013, y = .pi)) +
  geom_line(aes(color = as.factor(imdb_rating)), linewidth = 1) +
  facet_wrap(~ year) +
  labs(y = "Probability of Passing Test")
```

```{r}
movies2 <- movies2 |> as_tibble()
ggplot(data = movies2, aes(x = binary, y = metascore)) +
  geom_boxplot()

ggplot(data = movies2, aes(x = binary, y = imdb_rating)) +
  geom_boxplot()

movies2 <- movies2 |> mutate(profit = parse_number(intgross_2013) - budget_2013)

mod <- glm(binary_0 ~ metascore + imdb_rating + year + profit, data = movies2,
    family = "binomial") 

library(modelr)
grid <- movies2 |>
  data_grid(
    year = median(movies2$year, na.rm = TRUE),
    profit = median(movies2$profit, na.rm = TRUE),
    imdb_rating = seq_range(imdb_rating, n = 20),
    metascore = seq_range(metascore, n = 4)
    )


aug_year <- augment(mod, newdata = grid, se_fit = TRUE)
aug_year <- aug_year |> mutate(.pi = exp(.fitted) / (1 + exp(.fitted)))

ggplot(data = aug_year, aes(x = imdb_rating, y = .pi)) +
  geom_line(aes(colour = factor(metascore)))

## in general, higher imdb_rating is associated with lower prob of passing
## but, higher metascore (critics) is associated with higher probability of passing
```
