---
title: "Genre Analysis"
format: html
editor: visual
---


```{r message=F}
library(tidyverse)
library(tidytext)
library(textdata)
```


```{r message=FALSE, warning=FALSE}
# read in the data manually
raw_bechdel <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
movies <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')

afinn <- get_sentiments("afinn")
bing <- get_sentiments("bing")
nrc <- get_sentiments("nrc")
```

look into genre-
accounting for genre, difference in positivity scores? (facet)
separate line for every genre (movies have multiple lines) - similar to plot method

```{r}
movies2 <- read.csv("C:/Users/Hailey/OneDrive - St. Lawrence University/SYE/SYE/movies2.csv")
```


```{r}
movies_genre <- movies2 %>% unnest_tokens(output = "genre", input = "genre")
```


```{r}
movies_genre %>% 
  ggplot(mapping = aes(x = sentiment_score, y = binary, color = binary)) + 
  geom_boxplot() + # facet this plot by genre
  facet_wrap("genre")

movies_genre %>% 
  ggplot(mapping = aes(x = rough_score, y = binary, color = binary)) + 
  geom_boxplot() + # facet this plot by genre
  facet_wrap("genre")
```

```{r}
movies_genre %>% filter(genre == "action") %>%
  ggplot(mapping = aes(x = genre, y = sentiment_score, color = binary)) + 
  geom_boxplot() +
  coord_flip()


movies_genre %>% filter(genre == "action") %>%
  ggplot(mapping = aes(x = genre, y = rough_score, color = binary)) + 
  geom_boxplot() +
  coord_flip()
```



```{r}
movies_genre %>% filter(genre == "family") %>%
  ggplot(mapping = aes(x = genre, y = sentiment_score, color = binary)) + 
  geom_boxplot() +
  coord_flip()


movies_genre %>% filter(genre == "family") %>%
  ggplot(mapping = aes(x = genre, y = rough_score, color = binary)) + 
  geom_boxplot() +
  coord_flip()
```

```{r}
movies_genre %>% 
  group_by(year, binary) %>% summarise(n = n())
```


```{r}
movies_genre %>% 
  group_by(year, binary) %>% summarise(n = n()) %>% 
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```



```{r}
movies_genre %>% filter(genre == "action") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```

```{r}
movies_genre %>% filter(genre == "adventure") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```

```{r}
movies_genre %>% filter(genre == "comedy") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```

```{r}
movies_genre %>% filter(genre == "romance") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()

# be careful --> n is small**
```


```{r}
movies_genre %>% filter(genre == "fantasy") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```


```{r}
movies_genre %>% filter(genre == "sport") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()

# n is small
```

```{r}
movies_genre %>% filter(genre == "drama") %>% 
  group_by(year, binary) %>% summarise(n = n()) %>%
  ggplot(mapping = aes(x = year, y = n, color = binary)) +
  geom_point() + 
  geom_smooth()
```





